name: hotels_t
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.3.1 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  auto_route: ^7.8.0
  dio: ^5.3.3
  retrofit: ^4.0.3
  json_annotation: ^4.8.1
  flutter_bloc: ^8.1.3
  freezed: ^2.4.7
  freezed_annotation: ^2.4.1
  get_it: ^7.6.4
  cached_network_image: ^3.3.1
  url_launcher: ^6.2.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner:
  auto_route_generator: ^7.3.1
  retrofit_generator: '^8.0.1'
  json_serializable: ^6.6.2
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true

  fonts:
    - family: SFProDisplay
      fonts:
        - asset: assets/fonts/sfprodisplay/SF-Pro-Display-Bold.otf
        - asset: assets/fonts/sfprodisplay/SF-Pro-Display-Medium.otf
          weight: 700
        - asset: assets/fonts/sfprodisplay/SF-Pro-Display-Light.otf
          weight: 300
